//
// DO NOT EDIT THIS FILE, IT HAS BEEN GENERATED USING AndroidAnnotations 3.2.
//


package com.example.annotations;

import android.content.Context;
import android.os.Handler;
import android.os.Looper;
import android.util.Log;
import android.widget.TextView;
import com.example.annotations.R.id;
import org.androidannotations.api.BackgroundExecutor;
import org.androidannotations.api.view.HasViews;
import org.androidannotations.api.view.OnViewChangedListener;
import org.androidannotations.api.view.OnViewChangedNotifier;

public final class MainActions_
    extends MainActions
    implements OnViewChangedListener
{

    private Context context_;
    private Handler handler_ = new Handler(Looper.getMainLooper());

    private MainActions_(Context context) {
        context_ = context;
        init_();
    }

    public static MainActions_ getInstance_(Context context) {
        return new MainActions_(context);
    }

    private void init_() {
        OnViewChangedNotifier.registerOnViewChangedListener(this);
        if (context_ instanceof Annotations) {
            mActivity = ((Annotations) context_);
        } else {
            Log.w("MainActions_", (("Due to Context class "+ context_.getClass().getSimpleName())+", the @RootContext Annotations won't be populated"));
        }
        context = context_;
    }

    public void rebind(Context context) {
        context_ = context;
        init_();
    }

    @Override
    public void onViewChanged(HasViews hasViews) {
        tv1 = ((TextView) hasViews.findViewById(id.textView1));
    }

    @Override
    public void runInUiThread(final int result, final UiCallback uiCallback) {
        handler_.post(new Runnable() {


            @Override
            public void run() {
                MainActions_.super.runInUiThread(result, uiCallback);
            }

        }
        );
    }

    @Override
    public void doActionsInThread(final int params, final UiCallback uiCallback) {
        BackgroundExecutor.execute(new BackgroundExecutor.Task("", 0, "") {


            @Override
            public void execute() {
                try {
                    MainActions_.super.doActionsInThread(params, uiCallback);
                } catch (Throwable e) {
                    Thread.getDefaultUncaughtExceptionHandler().uncaughtException(Thread.currentThread(), e);
                }
            }

        }
        );
    }

}
